#!/usr/bin/env bash
# ============================================
# lib/tunnel/ngrok.sh -- ngrok tunnel provider
#
# Implements: tunnel_start, tunnel_stop,
#   tunnel_status, tunnel_url
#
# Assumes lib/common.sh and lib/config.sh have
# already been sourced by the caller.
# ============================================

# ------------------------------------------
# Constants
# ------------------------------------------

TUNNEL_ENV="$CC_TMUX_DIR/tunnel.env"
TUNNEL_LOG="$CC_TMUX_DIR/tunnel.log"
WATCHDOG_PID_FILE="$CC_TMUX_DIR/tunnel-watchdog.pid"
NGROK_API="http://127.0.0.1:4040/api"

# ------------------------------------------
# Internal helpers (prefixed with underscore)
# ------------------------------------------

# Check if ngrok tcp process is running
_ngrok_is_running() {
    pgrep -f "ngrok tcp" &>/dev/null
}

# Check if ngrok local API responds
_ngrok_api_responds() {
    curl -sf "$NGROK_API/tunnels" &>/dev/null
}

# Extract tunnel address from ngrok API and persist to tunnel.env
_ngrok_persist_address() {
    local response public_url

    # Try /api/tunnels first (deprecated but functional)
    response=$(curl -sf "$NGROK_API/tunnels" 2>/dev/null)
    if [[ -n "$response" ]]; then
        public_url=$(echo "$response" | jq -r '.tunnels[0].public_url // empty' 2>/dev/null)
    fi

    # Fallback to /api/endpoints (new format)
    if [[ -z "${public_url:-}" ]]; then
        response=$(curl -sf "$NGROK_API/endpoints" 2>/dev/null)
        if [[ -n "$response" ]]; then
            public_url=$(echo "$response" | jq -r '.endpoints[0].url // empty' 2>/dev/null)
        fi
    fi

    if [[ -z "${public_url:-}" ]]; then
        return 1
    fi

    # Parse tcp://host:port format
    local host port
    host=$(echo "$public_url" | sed 's|tcp://||' | cut -d: -f1)
    port=$(echo "$public_url" | sed 's|tcp://||' | cut -d: -f2)

    # Persist to tunnel.env
    cat > "$TUNNEL_ENV" <<EOF
# Generated by cc-tmux tunnel -- do not edit manually
# Last updated: $(date "+%Y-%m-%d %H:%M:%S")
TUNNEL_HOST="$host"
TUNNEL_PORT="$port"
TUNNEL_URL="$public_url"
TUNNEL_PROVIDER="ngrok"
EOF
    chmod 600 "$TUNNEL_ENV"
}

# Check if watchdog process is alive
_watchdog_is_running() {
    if [[ ! -f "$WATCHDOG_PID_FILE" ]]; then
        return 1
    fi

    local pid
    pid=$(cat "$WATCHDOG_PID_FILE" 2>/dev/null)

    if [[ -z "$pid" ]]; then
        rm -f "$WATCHDOG_PID_FILE"
        return 1
    fi

    if kill -0 "$pid" 2>/dev/null; then
        return 0
    fi

    # Stale PID file -- process no longer exists
    rm -f "$WATCHDOG_PID_FILE"
    return 1
}

# Stop the watchdog process and clean up PID file
_ngrok_stop_watchdog() {
    if [[ -f "$WATCHDOG_PID_FILE" ]]; then
        local pid
        pid=$(cat "$WATCHDOG_PID_FILE" 2>/dev/null)
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null
            wait "$pid" 2>/dev/null
        fi
    fi
    rm -f "$WATCHDOG_PID_FILE"
}

# Start the watchdog background loop
_ngrok_start_watchdog() {
    _ngrok_stop_watchdog

    # Truncate log to last 500 lines before starting
    if [[ -f "$TUNNEL_LOG" ]]; then
        tail -n 500 "$TUNNEL_LOG" > "${TUNNEL_LOG}.tmp" && mv "${TUNNEL_LOG}.tmp" "$TUNNEL_LOG"
    fi

    # The watchdog runs in a nohup subshell -- it cannot call
    # parent shell functions, so address persistence is inlined.
    nohup bash -c '
        tunnel_env="'"$TUNNEL_ENV"'"
        tunnel_log="'"$TUNNEL_LOG"'"
        ngrok_api="'"$NGROK_API"'"
        backoff=30
        max_backoff=300

        while true; do
            sleep 30

            # Health check: process running AND API responding
            if ! pgrep -f "ngrok tcp" &>/dev/null || \
               ! curl -sf "${ngrok_api}/tunnels" &>/dev/null; then

                echo "[$(date "+%Y-%m-%d %H:%M:%S")] Tunnel down, restarting (backoff: ${backoff}s)..." \
                    >> "$tunnel_log"

                # Kill any leftover ngrok processes
                pkill -f "ngrok tcp" 2>/dev/null
                sleep 2

                # Start fresh ngrok instance
                nohup ngrok tcp 22 --log=stdout >> "$tunnel_log" 2>&1 &

                # Wait for API to become available
                api_up=false
                for i in $(seq 1 15); do
                    if curl -sf "${ngrok_api}/tunnels" &>/dev/null; then
                        api_up=true
                        break
                    fi
                    sleep 1
                done

                if [[ "$api_up" == "true" ]]; then
                    # Persist new address (inlined -- cannot call functions)
                    response=$(curl -sf "${ngrok_api}/tunnels" 2>/dev/null)
                    public_url=""
                    if [[ -n "$response" ]]; then
                        public_url=$(echo "$response" | jq -r ".tunnels[0].public_url // empty" 2>/dev/null)
                    fi
                    if [[ -z "$public_url" ]]; then
                        response=$(curl -sf "${ngrok_api}/endpoints" 2>/dev/null)
                        if [[ -n "$response" ]]; then
                            public_url=$(echo "$response" | jq -r ".endpoints[0].url // empty" 2>/dev/null)
                        fi
                    fi
                    if [[ -n "$public_url" ]]; then
                        host=$(echo "$public_url" | sed "s|tcp://||" | cut -d: -f1)
                        port=$(echo "$public_url" | sed "s|tcp://||" | cut -d: -f2)
                        cat > "$tunnel_env" <<ENVEOF
# Generated by cc-tmux tunnel -- do not edit manually
# Last updated: $(date "+%Y-%m-%d %H:%M:%S")
TUNNEL_HOST="$host"
TUNNEL_PORT="$port"
TUNNEL_URL="$public_url"
TUNNEL_PROVIDER="ngrok"
ENVEOF
                        chmod 600 "$tunnel_env"
                    fi

                    echo "[$(date "+%Y-%m-%d %H:%M:%S")] Tunnel restored" >> "$tunnel_log"
                    backoff=30
                else
                    backoff=$((backoff * 2))
                    (( backoff > max_backoff )) && backoff=$max_backoff
                    echo "[$(date "+%Y-%m-%d %H:%M:%S")] Restart failed, next attempt in ${backoff}s" \
                        >> "$tunnel_log"
                fi
            fi
        done
    ' >> "$TUNNEL_LOG" 2>&1 &

    echo $! > "$WATCHDOG_PID_FILE"
}

# ------------------------------------------
# Public functions (required by provider interface)
# ------------------------------------------

# Start ngrok tunnel, persist address, launch watchdog
tunnel_start() {
    # Guard: already running
    if _ngrok_is_running && _ngrok_api_responds; then
        log_ok "Tunnel already running"
        tunnel_url
        return 0
    fi

    # Check ngrok authentication
    if ! ngrok config check &>/dev/null; then
        log_error "ngrok not authenticated"
        log_hint "Run: ngrok config add-authtoken YOUR_TOKEN"
        return 1
    fi

    # Kill any leftover ngrok processes
    pkill -f "ngrok tcp" 2>/dev/null
    sleep 1

    # Start ngrok in background
    nohup ngrok tcp 22 --log=stdout > "$TUNNEL_LOG" 2>&1 &

    # Wait for API to become available (poll with timeout)
    local attempts=0
    local max_attempts=15
    while (( attempts < max_attempts )); do
        if curl -sf "$NGROK_API/tunnels" &>/dev/null; then
            break
        fi
        sleep 1
        ((attempts++))
    done

    if (( attempts >= max_attempts )); then
        log_error "ngrok failed to start (API not responding after ${max_attempts}s)"
        # Check for payment-related errors
        if [[ -f "$TUNNEL_LOG" ]] && grep -qi "payment\|billing\|upgrade\|paid" "$TUNNEL_LOG" 2>/dev/null; then
            log_hint "TCP tunnels require a payment method on file at"
            log_hint "https://dashboard.ngrok.com/settings#id-verification"
            log_hint "(you won't be charged)"
        fi
        pkill -f "ngrok tcp" 2>/dev/null
        return 1
    fi

    # Extract and persist address
    if ! _ngrok_persist_address; then
        log_warn "Could not determine tunnel address"
    fi

    # Start health watchdog
    _ngrok_start_watchdog

    log_ok "Tunnel started"
    tunnel_url
}

# Stop ngrok tunnel and watchdog
tunnel_stop() {
    _ngrok_stop_watchdog
    pkill -f "ngrok tcp" 2>/dev/null
    log_ok "Tunnel stopped"
}

# Show tunnel status (human-readable or --json)
tunnel_status() {
    local provider="ngrok"
    local status="down"
    local host="" port="" watchdog_status="stopped"

    if _ngrok_is_running && _ngrok_api_responds; then
        status="connected"
        _ngrok_persist_address  # Refresh persisted address
    elif _ngrok_is_running; then
        status="reconnecting"
    fi

    # Read persisted address (works even when tunnel is down)
    if [[ -f "$TUNNEL_ENV" ]]; then
        # shellcheck source=/dev/null
        source "$TUNNEL_ENV"
        host="${TUNNEL_HOST:-}"
        port="${TUNNEL_PORT:-}"
    fi

    # Check watchdog
    if _watchdog_is_running; then
        watchdog_status="running"
    fi

    if [[ "${1:-}" == "--json" ]]; then
        printf '{"provider":"%s","status":"%s","host":"%s","port":"%s","watchdog":"%s"}\n' \
            "$provider" "$status" "$host" "$port" "$watchdog_status"
    else
        echo ""
        echo "  Tunnel Status"
        echo "  -------------"
        echo "  Provider:  $provider"
        echo "  Status:    $status"
        echo "  Host:      ${host:-n/a}"
        echo "  Port:      ${port:-n/a}"
        echo "  Watchdog:  $watchdog_status"
        if [[ "$status" == "connected" && -n "$host" ]]; then
            echo ""
            echo "  Connect:   ssh -p $port $USER@$host"
        fi
        echo ""
    fi
}

# Return persisted tunnel address as host:port
tunnel_url() {
    if [[ -f "$TUNNEL_ENV" ]]; then
        # shellcheck source=/dev/null
        source "$TUNNEL_ENV"
        if [[ -n "${TUNNEL_HOST:-}" ]]; then
            echo "${TUNNEL_HOST}:${TUNNEL_PORT}"
            return 0
        fi
    fi
    return 1
}
