#!/usr/bin/env bash
# ============================================
# lib/config.sh -- Configuration management
#
# Provides: Read/write operations for
#   ~/.cc-tmux/config.env (KEY="value" format)
#   ~/.cc-tmux/projects.conf (name|path format)
#
# Assumes lib/common.sh has already been sourced
# by the caller (uses log_ok, log_error, etc.).
# ============================================

# ------------------------------------------
# Config paths
# ------------------------------------------

CC_TMUX_DIR="$HOME/.cc-tmux"
CONFIG_FILE="$CC_TMUX_DIR/config.env"
PROJECTS_FILE="$CC_TMUX_DIR/projects.conf"

# ------------------------------------------
# Directory management
# ------------------------------------------

ensure_config_dir() {
    mkdir -p "$CC_TMUX_DIR"
    chmod 700 "$CC_TMUX_DIR"
}

# ------------------------------------------
# config.env operations
# ------------------------------------------

write_config() {
    # Takes key-value pairs: write_config KEY1 "val1" KEY2 "val2"
    ensure_config_dir

    if [[ ! -f "$CONFIG_FILE" ]]; then
        # Create new config with header
        {
            echo "# Generated by cc-tmux installer -- hand-editable"
            echo "# Last updated: $(date +%Y-%m-%d)"
            echo ""
        } > "$CONFIG_FILE"
        chmod 600 "$CONFIG_FILE"
    else
        # Update the timestamp in existing file
        if grep -q "^# Last updated:" "$CONFIG_FILE" 2>/dev/null; then
            sed -i "s/^# Last updated:.*$/# Last updated: $(date +%Y-%m-%d)/" "$CONFIG_FILE"
        fi
    fi

    # Process key-value pairs
    while [[ $# -ge 2 ]]; do
        local key="$1"
        local value="$2"
        shift 2

        if grep -q "^${key}=" "$CONFIG_FILE" 2>/dev/null; then
            # Update existing key
            sed -i "s|^${key}=.*$|${key}=\"${value}\"|" "$CONFIG_FILE"
        else
            # Append new key
            echo "${key}=\"${value}\"" >> "$CONFIG_FILE"
        fi
    done
}

read_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        # shellcheck source=/dev/null
        source "$CONFIG_FILE"
    else
        log_error "Config not found: $CONFIG_FILE"
        log_hint "Run install.sh first"
        return 1
    fi
}

get_config() {
    local key="$1"

    if [[ ! -f "$CONFIG_FILE" ]]; then
        log_error "Config not found: $CONFIG_FILE"
        return 1
    fi

    # Source config in a subshell to avoid polluting current env
    local value
    value=$(
        # shellcheck source=/dev/null
        source "$CONFIG_FILE"
        echo "${!key}"
    )

    if [[ -n "$value" ]]; then
        echo "$value"
        return 0
    else
        return 1
    fi
}

# ------------------------------------------
# projects.conf operations
# ------------------------------------------

add_project() {
    local name="$1"
    local path="$2"

    # Validate name
    if [[ -z "$name" ]]; then
        log_error "Project name cannot be empty"
        return 1
    fi
    if [[ "$name" == *"|"* ]]; then
        log_error "Project name cannot contain pipe character: $name"
        return 1
    fi

    # Validate path
    if [[ "$path" != /* ]]; then
        log_error "Project path must be absolute (start with /): $path"
        return 1
    fi

    ensure_config_dir

    # Check for duplicate (idempotent)
    if [[ -f "$PROJECTS_FILE" ]] && grep -q "^${name}|" "$PROJECTS_FILE" 2>/dev/null; then
        log_warn "Project '$name' already exists -- skipping"
        return 0
    fi

    echo "${name}|${path}" >> "$PROJECTS_FILE"
    log_ok "Added project: $name -> $path"
}

remove_project() {
    local name="$1"

    if [[ ! -f "$PROJECTS_FILE" ]]; then
        log_warn "No projects file found"
        return 0
    fi

    if grep -q "^${name}|" "$PROJECTS_FILE" 2>/dev/null; then
        grep -v "^${name}|" "$PROJECTS_FILE" > "${PROJECTS_FILE}.tmp"
        mv "${PROJECTS_FILE}.tmp" "$PROJECTS_FILE"
        log_ok "Removed project: $name"
    else
        log_warn "Project '$name' not found"
    fi
}

list_projects() {
    if [[ ! -f "$PROJECTS_FILE" ]] || [[ ! -s "$PROJECTS_FILE" ]]; then
        log_warn "No projects configured"
        return 1
    fi

    echo ""
    echo "  Configured projects:"
    echo "  ---------------------"
    local idx=1
    while IFS='|' read -r name path; do
        echo "  $idx. $name -> $path"
        ((idx++))
    done < "$PROJECTS_FILE"
    echo ""
}

project_count() {
    if [[ -f "$PROJECTS_FILE" ]] && [[ -s "$PROJECTS_FILE" ]]; then
        wc -l < "$PROJECTS_FILE" | tr -d ' '
    else
        echo "0"
    fi
}
